# Generated by Django 5.0.4 on 2024-08-01 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0003_department_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="company_id",
            new_name="company",
        ),
    ]
