version: 3.8


services:
  web:
    build: .
    command: python manage.py runserver
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file: ./erp/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./erp/.env
    # environment:
    #   - DB_USER=apple
    #   - DB_PASS=
    #   - DB_NAME=erp
    #   - DB_HOST=localhost
    #   - DB_PORT=5432


volumes:
  postgres_data:
