# Generated by Django 5.0.4 on 2024-07-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auths", "0001_initial"),
        ("departments", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payroll_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_payroll",
                to="payroll.payroll",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="departments.position"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
