# Generated by Django 5.0.4 on 2024-07-28 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="payroll_id",
        ),
    ]
