# Generated by Django 5.0.4 on 2024-07-28 17:03

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bill_of_quantity", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("completed", "completed"),
                            ("inprogress", "inprogress"),
                            ("terminated", "terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="document"
                    ),
                ),
                ("working_time", models.DateTimeField(auto_now_add=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_projects",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "boq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="bill_of_quantity.billofquantity",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head_of_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_project_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="project.project",
                    ),
                ),
                (
                    "sub_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_project_details",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("material_requisition", models.CharField(max_length=150)),
                ("material_consumed", models.CharField(max_length=150)),
                ("material_planning", models.CharField(max_length=150)),
                ("hours_planned", models.DateTimeField()),
                ("stage", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectIssues",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "assigned"),
                            ("unassigned", "unassigned"),
                            ("completed", "completed"),
                        ],
                        default="unassigned",
                        max_length=20,
                    ),
                ),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="project.project",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_issues",
                        to="project.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hours_per_week", models.TimeField()),
                ("working_time", models.TimeField()),
                ("day_of_the_week", models.CharField(max_length=10)),
                ("work_from", models.TimeField()),
                ("work_to", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="project.project",
                    ),
                ),
                (
                    "working_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
