# Generated by Django 5.0.4 on 2024-08-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="details",
            name="client",
        ),
        migrations.RemoveField(
            model_name="details",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="project",
            name="manager",
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
