# Generated by Django 5.0.4 on 2024-08-01 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_details_client_remove_details_contractor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="details",
            old_name="projectId",
            new_name="project_id",
        ),
    ]
