# Generated by Django 5.0.4 on 2024-08-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill_of_quantity", "0002_initial"),
        ("project", "0003_rename_projectid_details_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="boq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="bill_of_quantity.billofquantity",
            ),
        ),
    ]
