# Generated by Django 5.0.4 on 2024-08-01 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_details_boq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="projectId",
            new_name="project",
        ),
    ]
