# Generated by Django 5.0.4 on 2024-07-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("appraisalDate", models.DateTimeField()),
                ("score", models.FloatField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "appraisedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraised_appraisals",
                        to="auths.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_appraisals",
                        to="auths.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("designation", models.CharField(max_length=100)),
                ("pay_start_period", models.DateTimeField()),
                ("pay_end_period", models.DateTimeField()),
                ("gross_salary", models.FloatField()),
                ("deductions", models.FloatField()),
                ("net_salary", models.FloatField()),
                ("annual_gross_salary", models.FloatField()),
                ("annual_deductions", models.FloatField()),
                ("annual_net_salary", models.FloatField()),
                ("allowances", models.FloatField()),
                ("pay_date", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "appraisal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payrolls",
                        to="payroll.appraisal",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="auths.employee",
                    ),
                ),
            ],
        ),
    ]
