# Generated by Django 5.0.4 on 2024-10-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
        ('project', '0005_rename_projectid_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook', to='project.project'),
        ),
    ]
