# Generated by Django 5.0.4 on 2024-09-04 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="item_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisitions",
                to="items.item",
            ),
        ),
    ]
