# Generated by Django 5.0.4 on 2024-09-14 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_alter_requisition_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisition",
            name="item_id",
        ),
    ]
