# Generated by Django 5.0.4 on 2024-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_remove_requisition_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="complain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
