# Generated by Django 5.0.4 on 2024-10-06 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_customuser_groups_and_more'),
        ('purchase', '0004_requisition_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='approve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_app_requisitions', to='auths.employee'),
        ),
    ]
