# Generated by Django 5.0.4 on 2024-07-28 17:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("zipcode", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=50)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("site_address", models.CharField(max_length=255)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
