# Generated by Django 5.0.4 on 2024-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillOfQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("equipment_cost", models.FloatField()),
                ("estimated_cost", models.FloatField()),
                ("sub_contractor_cost", models.FloatField(blank=True, null=True)),
                ("material_cost", models.FloatField()),
                ("labour_cost", models.FloatField()),
                ("mark_up_cost", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("unitMeasurement", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("rate", models.FloatField()),
                ("total", models.FloatField()),
            ],
        ),
    ]
