# Generated by Django 5.0.4 on 2024-07-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bill_of_quantity", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofquantity",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boq_project",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="billofquantity",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boq_keys",
                to="bill_of_quantity.key",
            ),
        ),
    ]
