# Generated by Django 5.0.4 on 2024-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill_of_quantity", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofquantity",
            name="equipment_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billofquantity",
            name="estimated_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billofquantity",
            name="labour_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billofquantity",
            name="mark_up_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billofquantity",
            name="material_cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
