# Generated by Django 5.0.4 on 2024-09-28 14:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bill_of_quantity", "0003_alter_billofquantity_equipment_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofquantity",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
